#!/bin/bash
apt update

# Install nginx
apt install -y nginx

# Enable nginx to start on boot
systemctl enable nginx

# Setup Let's Encrypt
apt install -y python3-acme python3-certbot python3-mock python3-openssl python3-pkg-resources python3-pyparsing python3-zope.interface
apt install -y python3-certbot-nginx

# Install certificate
certbot --nginx -d DOMAIN --non-interactive --agree-tos -m devops@bhoos.com

# Reverse proxy configuration to be stored on a per domain basis at
#   /etc/nginx/sites-available/DOMAIN_NAME
#   ln -s /etc/nginx/sites-available/DOMAIN_NAME /etc/nginx/sites-enabled/DOMAIN_NAME
# Setup a reverse proxy server to the node app
echo "
server {
  listen 443 ssl;
  server_name DOMAIN_NAME;
  
  location / {
    proxy_pass http://10.104.0.X:3000;
  }
}
" > /etc/nginx/sites-available/DOMAIN_NAME
# Link the configuration
ln -s /etc/nginx/sites-available/DOMAIN_NAME /etc/nginx/sites-enabled/DOMAIN_NAME

systemctl reload nginx
